"""Constants for the Enody integration."""

DOMAIN = "enody"
MANUFACTURER = "Enody"

CONF_ENDPOINT = "endpoint"
CONF_TOKEN = "token"

MODEL = "EP01"
DEFAULT_WIFI_PORT = 8788
DEFAULT_SCAN_INTERVAL_SECONDS = 30

MIN_COLOR_TEMP_KELVIN = 1000
MAX_COLOR_TEMP_KELVIN = 5000
DEFAULT_COLOR_TEMP_KELVIN = 2700
DEFAULT_XY_COLOR = (0.3127, 0.3290)

PAIRING_PROGRESS_ACTION = "pair"
